# Generated by Django 5.2.17 on 2026-09-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='model_choice',
            field=models.CharField(choices=[('claude-opus-5', 'Claude Opus 5 (Azure Anthropic)'), ('gemini-3.6-flash', 'Gemini 3.6 Flash (Google GenAI)'), ('hybrid', 'Multi-Model (Claude Tutor + Gemini Evaluator)')], default='claude-opus-5', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='model_used',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='evaluator_model',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
