# Generated by Django 5.2.17 on 2026-09-05 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Student', max_length=120)),
                ('phone_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('grade', models.CharField(blank=True, default='10', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120)),
                ('mastery_score', models.IntegerField(default=0)),
                ('sessions_completed', models.IntegerField(default=0)),
                ('last_studied', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Progress records',
                'ordering': ['-last_studied'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
